-- Script de création et de population des tables liées au Gros_Singe

BEGIN TRANSACTION;
DROP TABLE IF EXISTS taquets;
DROP TABLE IF EXISTS patterns;

CREATE TABLE patterns(key, pattern);
CREATE TABLE taquets(key, text, output);
INSERT INTO "taquets" VALUES('gratuit','te chie dans la bouche, nick, et ça te pique les yeux.','action');
INSERT INTO "taquets" VALUES('gratuit','met une calotte sur sa bouche à nick.','action');
INSERT INTO "taquets" VALUES('gratuit','slappe nick avec une truite large.','action');
INSERT INTO "taquets" VALUES('gratuit','met un taquet à nick.','action');
INSERT INTO "taquets" VALUES('gratuit','pense que nick est un gros gay.','action');
INSERT INTO "taquets" VALUES('gratuit','jette une enclume sur nick.','action');
INSERT INTO "taquets" VALUES('gratuit','jette un tabouret à la gueule de nick.','action');
INSERT INTO "taquets" VALUES('gratuit','fait un bisou à nick.','action');
INSERT INTO "taquets" VALUES('gratuit','vomit sur nick.','action');
INSERT INTO "taquets" VALUES('gratuit','envoie un coup de pied retourné dans la figure de nick.','action');
INSERT INTO "taquets" VALUES('gratuit','assomme nick.','action');
INSERT INTO "taquets" VALUES('gratuit','fait une clef de bras à nick.','action');
INSERT INTO "taquets" VALUES('gratuit','savate nick.','action');
INSERT INTO "taquets" VALUES('gratuit','se demande si nick est toujours pédé.','action');
INSERT INTO "taquets" VALUES('gratuit','pense que nick est un poil de bite.','action');
INSERT INTO "taquets" VALUES('gratuit','se fout de ta vie, nick...','action');
INSERT INTO "taquets" VALUES('gratuit','trouve que nick a une tronche d''accident.','action');
INSERT INTO "taquets" VALUES('gratuit','s''assied sur nick.','action');
INSERT INTO "taquets" VALUES('gratuit','gicle sur nick.','action');
INSERT INTO "taquets" VALUES('gratuit','se dit que nick est un GROS CON !','action');
INSERT INTO "taquets" VALUES('gratuit','fait caca sur nick.','action');
INSERT INTO "taquets" VALUES('gratuit','regarde nick, dégoûté.','action');
INSERT INTO "taquets" VALUES('gratuit','arrache la tête de nick et lui chie dans le cou.','action');
INSERT INTO "taquets" VALUES('gratuit','arrache un œil de nick et lui baise le crâne.','action');
INSERT INTO "taquets" VALUES('gratuit','s''essuie les pieds sur nick.','action');
INSERT INTO "taquets" VALUES('gratuit','crache sur nick.','action');
INSERT INTO "taquets" VALUES('gratuit','lance un morceau de savon à nick.','action');
INSERT INTO "taquets" VALUES('gratuit','regarde nick parler, et comprend maintenant d''où vient cette odeur d''égoûts.','action');
INSERT INTO "taquets" VALUES('gratuit','lâche une caisse au visage de nick.','action');
INSERT INTO "taquets" VALUES('gratuit','aperçoit nick, sourit, et sort un bocal de verre pilé et un sac de gravats.','action');
INSERT INTO "taquets" VALUES('gratuit','se dit que nick doit être mignon quand il envoie la purée...','action');
INSERT INTO "taquets" VALUES('gratuit','lance un iPhone sur nick.','action');
INSERT INTO "taquets" VALUES('gratuit','secoue nick et regarde tomber les morpions.','action');
INSERT INTO "taquets" VALUES('gratuit','a honte de partager le même chan que nick.','action');
INSERT INTO "taquets" VALUES('gratuit','se cure le nez et s''essuie les doigts sur nick.','action');
INSERT INTO "taquets" VALUES('bavard','Tu parles trop, nick !','loud');
INSERT INTO "taquets" VALUES('bavard','Mais faites-le taire !','loud');
INSERT INTO "taquets" VALUES('bavard','Tu vois pas que personne ne t''écoute ?','loud');
INSERT INTO "taquets" VALUES('bavard','J''ai une idée ! Et si tu arrêtais de parler ? Là, tout de suite ?','loud');
INSERT INTO "taquets" VALUES('question','À ton avis ?','loud');
INSERT INTO "taquets" VALUES('question','Devine !','loud');
INSERT INTO "taquets" VALUES('question','T''as de ces questions, toi...','loud');
INSERT INTO "taquets" VALUES('question','T''as pas une petite idée ?','loud');
INSERT INTO "taquets" VALUES('exclamation','Sérieux ??? Mais c''est OUF !!!','loud');
INSERT INTO "taquets" VALUES('exclamation','Roooh lala le truc de gueudin !','loud');
INSERT INTO "taquets" VALUES('exclamation','Eh ben dis-donc !','loud');
INSERT INTO "taquets" VALUES('exclamation','Mais t''as une vie trépidente, toi !','loud');
INSERT INTO "taquets" VALUES('hilight','court se cacher.','action');
INSERT INTO "taquets" VALUES('hilight','Taggle nick !!!','loud');
INSERT INTO "taquets" VALUES('hilight','fait un sourire à nick.','action');
INSERT INTO "taquets" VALUES('hilight','Fais pas le malin, toi !','loud');
INSERT INTO "taquets" VALUES('hilight','Mais je t''emmerde !','loud');
INSERT INTO "taquets" VALUES('hilight','Ferme-là, nick, vraiment. S''il te plaît.','loud');
INSERT INTO "taquets" VALUES('lol','Tu trouves ça drôle ?','loud');
INSERT INTO "taquets" VALUES('lol','Et ça te fait rire ?','loud');
INSERT INTO "taquets" VALUES('lol','Et tu connais celle des deux pédés dans un ascenseur ?','loud');
INSERT INTO "taquets" VALUES('lol', 'ne voit pas ce qu''il y a de drôle...', 'action');
INSERT INTO "taquets" VALUES('init','est de retour.','action');
INSERT INTO "taquets" VALUES('init','est de nouveau dans la place.','action');
INSERT INTO "taquets" VALUES('init','C''est moi que v''là !','loud');
INSERT INTO "taquets" VALUES('merde','C''est toi la merde !','loud');
INSERT INTO "taquets" VALUES('oignon','Ah, les amis, vous dire c''que c''est bon, quand i''m''la care dans l''oignoooooooon !!!','loud');
INSERT INTO "taquets" VALUES('casse','Casse-toi pôv''con !!!','loud');
INSERT INTO "taquets" VALUES('metal','EVIL IN LEAGUE WITH SATAN !!!','loud');
INSERT INTO "taquets" VALUES('dtc','Dans ton cul !!!','loud');
INSERT INTO "taquets" VALUES('canard','Tu te prends pour un canard, nick ?','loud');
INSERT INTO "taquets" VALUES('canard','Coin coin !','loud');
INSERT INTO "taquets" VALUES('canard','Coin coin coin !','loud');
INSERT INTO "taquets" VALUES('canard','se demande pourquoi nick marche en canard.','action');
INSERT INTO "taquets" VALUES('rock','\\m/ ROCK''N ROLL !!! \\m/','loud');
INSERT INTO "taquets" VALUES('proute','Proutes interdits !','loud');
INSERT INTO "taquets" VALUES('proute','Ça pue ici, non ?','loud');
INSERT INTO "taquets" VALUES('cmb','Un complexe, nick ?','loud');
INSERT INTO "taquets" VALUES('tonton', 'verse une larme à la mémoire de Tonton.', 'action');
INSERT INTO "taquets" VALUES('tonton','Happy birthday Tonton !','loud');
INSERT INTO "taquets" VALUES('tonton','On t''aime, Tonton !','loud');
INSERT INTO "taquets" VALUES('moije','Moi je... moi je... mais ON S''EN BRANLE DE TA VIE !!!','loud');
INSERT INTO "taquets" VALUES('maman','Ah non, on avait dit pas les mères !','loud');
INSERT INTO "taquets" VALUES('8=>','Classe, la bite !','loud');
INSERT INTO "taquets" VALUES('quebec','Tape moé dans l''fond, maudzit Français !!!','loud');
INSERT INTO "taquets" VALUES('u','Poil au cul !!!','loud');
INSERT INTO "taquets" VALUES('enorme','Comme ma bite !!!','loud');
INSERT INTO "taquets" VALUES('longue','Comme ma bite !!!','loud');
INSERT INTO "taquets" VALUES('\o/','Baisse les bras s''il te plaît, nick, ou alors mets du déodorant.','loud');
INSERT INTO "taquets" VALUES('stoi','C''est toi le #{$2} !','loud');
INSERT INTO "taquets" VALUES(':p', 'coupe la langue de nick.', 'loud');
INSERT INTO "taquets" VALUES('afrique','Bombe atomique !','loud');
INSERT INTO "taquets" VALUES('supreme','Moi, quand je pète dans mon lit, eh ben j''secoue les draps !!!','loud');
INSERT INTO "taquets" VALUES('canard','C''est toi le canard !','loud');
INSERT INTO "taquets" VALUES('canard','Stoi le canard !!!','loud');
INSERT INTO "taquets" VALUES('canard','stoilcanard','loud');
INSERT INTO "taquets" VALUES('canard','Stoi le canard !','loud');
INSERT INTO "taquets" VALUES('canard','C''est toi le canard','loud');
INSERT INTO "taquets" VALUES('canard','C''est toi le canard !','loud');
INSERT INTO "taquets" VALUES('question','C''est vraiment une question à deux balles, ça...','loud');
INSERT INTO "taquets" VALUES('lol','Il en faut peu pour te faire rire, toi...','loud');
INSERT INTO "taquets" VALUES('question','Aucune idée !','loud');
INSERT INTO "taquets" VALUES('exclamation','Ah ouais ?','loud');
INSERT INTO "taquets" VALUES('question','J''en sais rien, et pour tout dire, j''m''en contre-branle la bite.','loud');
INSERT INTO "taquets" VALUES('lol','ne voit pas ce qu''il y a de drôle...','action');
INSERT INTO "taquets" VALUES(':p','coupe la langue de nick.','action');
INSERT INTO "taquets" VALUES('canard','QUACK !!!','loud');
INSERT INTO "taquets" VALUES('tonton','verse une larme à la mémoire de Tonton.','action');
INSERT INTO "taquets" VALUES('merde','Cacaa!!!','loud');
INSERT INTO "taquets" VALUES('question','Et ta soeur ?','loud');
INSERT INTO "taquets" VALUES('enorme','Comme la bite de Duncan !','loud');
INSERT INTO "taquets" VALUES('gratuit','attrape nick par les testiboules et lui fait faire la toupie.','action');
INSERT INTO "taquets" VALUES('question','oui','loud');
INSERT INTO "taquets" VALUES('question','non','loud');
INSERT INTO "taquets" VALUES('question','bien sûr !','loud');
INSERT INTO "taquets" VALUES('question','Je crois pas, non.','loud');
INSERT INTO "taquets" VALUES('gratuit','se gratte la bite et colle ses morpions sur nick.','action');
INSERT INTO "taquets" VALUES('exclamation','On s''en fout !','loud');
INSERT INTO "taquets" VALUES('exclamation','MER IL ET FOU !!!!!!!!!','loud');
INSERT INTO "taquets" VALUES('exclamation','C''est vraiment pédé, ça.','loud');
INSERT INTO "taquets" VALUES('question','Pourquoi, t''es de la police ?','loud');
INSERT INTO "taquets" VALUES('gratuit','pistonne nick.','action');
INSERT INTO "taquets" VALUES('gratuit','paye une pute à nick.','action');
INSERT INTO "taquets" VALUES('canard','Tu connais celle du canard pédé ?','loud');
INSERT INTO "taquets" VALUES('canard','va s''assoir dans un coin.','action');
INSERT INTO "taquets" VALUES('gratuit','bouse sur nick.','action');
INSERT INTO "taquets" VALUES('moije','Et moi, hier, j''ai mangé une banane.','loud');
INSERT INTO "taquets" VALUES('proute','retient son souffle et ferme les yeux.','action');
INSERT INTO "taquets" VALUES('gratuit','assomme nick avec un iPad.','action');
INSERT INTO "taquets" VALUES('exclamation','Ouais !!!','loud');
INSERT INTO "taquets" VALUES('canard','pan !!','loud');

INSERT INTO patterns VALUES('lol', '^lol$');
INSERT INTO patterns VALUES('merde', '^(.* )?merde( .*)?$');
INSERT INTO patterns VALUES('oignon', '^(.* )?oignons?( .*)?$');
INSERT INTO patterns VALUES('casse', '^(.* )?casse( .*)?$');
INSERT INTO patterns VALUES('metal', '^(.* )?metal( .*)?$');
INSERT INTO patterns VALUES('dtc', '^(.* )?où( .*)?\?$');
INSERT INTO patterns VALUES('canard', '^(.* )?(((o|ø|0)<)|(>(o|ø|0)))( .*)?$');
INSERT INTO patterns VALUES('rock', '^(.* )?rock( .*)?$');
INSERT INTO patterns VALUES('proute', '^(.* )?proute?( .*)?$');
INSERT INTO patterns VALUES('cmb', '^cmb$');
INSERT INTO patterns VALUES('tonton', '^(.* )?tonton( .*)?$');
INSERT INTO patterns VALUES('moije', '^moi\sj(e\s|\'').+$');
INSERT INTO patterns VALUES('maman', '^(.* )?(m(e|è)re|maman)( .*)?$');
INSERT INTO patterns VALUES('8=>', '^(8=+>)|(<=+8)$');
INSERT INTO patterns VALUES('quebec', '^(.* )?qu(e|é)b(e|é|è)c(ois|oise|oises)?( .*)?$');
INSERT INTO patterns VALUES('u', '^(.*)([^aeiouyqg]ue?)$');
INSERT INTO patterns VALUES('enorme', '^(.* )?(e|é|É)normes?( .*)?$');
INSERT INTO patterns VALUES('longue', '^(.* )?longues?( .*)?$');
INSERT INTO patterns VALUES('\o/', '^(.* )?(\\o\/)( .*)?$');
INSERT INTO patterns VALUES(':p', '^:p$');
INSERT INTO patterns VALUES('exclamation', '^(.*)!$');
INSERT INTO patterns VALUES('question', '^(.*)\?$');
INSERT INTO patterns VALUES('afrique', '^(.*)?afrique( .*)?$');
INSERT INTO patterns VALUES('supreme', '^(.*)?supr(e|ê)me( .*)?$');
INSERT INTO patterns VALUES('hehe', '^(e|ê)me( .*)?$');
INSERT INTO patterns VALUES('hilight', '^(.* )?#{@nick}[:)]?( .*)?$');
INSERT INTO patterns VALUES('stoi', '^(.* )?(\w{7})( .*)?$');

COMMIT;
