-- Script d'initialisation des citations pour Gros_Singe.
DROP TABLE IF EXISTS citations;
CREATE TABLE citations(key, text);

INSERT INTO citations VALUES('dinerdecons', 'Ah, je crois qu''on va avoir besoin de moi !');
INSERT INTO citations VALUES('dinerdecons', 'Il y avait un bibelot !');
INSERT INTO citations VALUES('dinerdecons', 'Comme on dit dans mon village : le coq est lâché, gardez vos poules.');
INSERT INTO citations VALUES('dinerdecons', 'J''avais dit « à gauche », Pignon...');
INSERT INTO citations VALUES('dinerdecons', 'Ah bon, il a pas de prénom ?');
INSERT INTO citations VALUES('dinerdecons', 'Il s''appelle Juste Leblanc.');
INSERT INTO citations VALUES('dinerdecons', 'La tour Eiffel… entièrement faite avec des alumettes, 346 422 exactement !');
INSERT INTO citations VALUES('dinerdecons', 'Y''a pas de mal à se moquer des abrutis. Ils sont là pour ça, non ?');
INSERT INTO citations VALUES('dinerdecons', 'Vous faites peine à voir. On dirait un cheval qui a raté une haie. On vous abattrait sur un champs de course.');
INSERT INTO citations VALUES('dinerdecons', 'Vous n''avez pas de sœur ? Je lui ai dit qui est à l''appareil, et elle m''a dit : « sa sœur ».');
INSERT INTO citations VALUES('dinerdecons', 'Il a appelé Marlène !');
INSERT INTO citations VALUES('dinerdecons', 'J''pouvais pas savoir, moi. Elle me dit : « C''est Marlène Sasseur. » Avouez que c''est confusant.');
INSERT INTO citations VALUES('dinerdecons', 'Tous les types qui font de la planche à voile piquent la femme de leurs amis.');
INSERT INTO citations VALUES('dinerdecons', 'Monsieur Pignon, votre prénom à vous, c''est François, c''est juste ?');
INSERT INTO citations VALUES('dinerdecons', 'Et bien lui, c''est pareil, c''est Juste.');
INSERT INTO citations VALUES('dinerdecons', 'C''est bizarre, ça lui donne du corps, je trouve.');
INSERT INTO citations VALUES('dinerdecons', 'Leblanc, c''est son nom, et c''est Juste son prénom.');
INSERT INTO citations VALUES('dinerdecons', 'Il a une belle tête de vainqueur.');
INSERT INTO citations VALUES('dinerdecons', 'Il est mignon Monsieur Pignon, il est méchant Monsieur Brochant !');
INSERT INTO citations VALUES('dinerdecons', 'La classe mondiale... Peut-être même le champion du monde !');
INSERT INTO citations VALUES('dinerdecons', 'Non c’est normal, on vous a raté aujourd’hui, on ne va pas vous rater la semaine prochaine !');
INSERT INTO citations VALUES('dinerdecons', 'Je veux que tu reviennes tout de suite, Charlotte... Bien sûr tu te rhabilles, évidemment que tu t’rhabilles !');
INSERT INTO citations VALUES('dinerdecons', 'Houuuuu, alors ça c’est très tordu, mais bougrement intelligent.');
INSERT INTO citations VALUES('dinerdecons', 'C’est cruellement fatiguant d’être intelligent.');
INSERT INTO citations VALUES('dinerdecons', 'Ton père fait collection de louches ?');
INSERT INTO citations VALUES('dinerdecons', 'Non, Pierre. Pas papa.');
INSERT INTO citations VALUES('dinerdecons', 'Pas du tout ! Qu’est ce que tu vas chercher ? Tu me vois invitant le père de mon meilleur ami à un dîner de cons ?');
INSERT INTO citations VALUES('dinerdecons', 'Mais attention ! le vrai boomerang, le boomerang authentique, pas celui que l’on trouve dans les bazars pour touristes de Sydney et autre Camberra, le boomerang primitif, celui qui armait les fiers guerriers australiens depuis la nuit des temps, ce boomerang là à une dynamique, un mouvement dans l’espace quand il est bien lancé, que je qualifierait de... de miraculeux. Avec ça on vous décapite un kangourou à cinquante kilomètres heure !');
INSERT INTO citations VALUES('dinerdecons', 'Il est pas con tout de même !');
INSERT INTO citations VALUES('dinerdecons', 'Et il est tout seul dans son grand appartement à mélanger l’alcool et les médicaments et je suis très inquiet pour lui parce que je sais qu’on peut mourir d’amour...');
INSERT INTO citations VALUES('dinerdecons', 'Ne m’invitez jamais à un diner, j’aurais toujours un doute.');
INSERT INTO citations VALUES('dinerdecons', 'Je me souviens j’ai contrôlé un Brochant il y a 3 ans, Michel Brochant c’est un parent à vous ?');
INSERT INTO citations VALUES('dinerdecons', 'Vous êtes libre mercredi soir ??');
INSERT INTO citations VALUES('dinerdecons', 'Ah écoutez, moi je n''aime pas être grossier mais là il faut employer le mot : c''est un con !');
INSERT INTO citations VALUES('dinerdecons', 'Oh le con !!');
INSERT INTO citations VALUES('dinerdecons', 'On va passer une bonne soirée Monsieur Pignon, une très bonne soirée !');
INSERT INTO citations VALUES('dinerdecons', 'Y a des moments où j''ai vraiment l''impression qu''vous m''prenez pour un imbécile hein !');
INSERT INTO citations VALUES('dinerdecons', 'Si le bouquin est mauvais, pourquoi j''irai acheter les droits ? Ahahahahahaha!!!');
INSERT INTO citations VALUES('dinerdecons', 'Bon... On a assez perdu de temps comme ça. Ma femme a signé le roman de son nom de jeune fille, Christine Leguirec.');
INSERT INTO citations VALUES('dinerdecons', 'Je prends l''accent belge ?');
INSERT INTO citations VALUES('dinerdecons', 'Allôôôô ??? [gros accent belge] Pourrais-je parler à Monsieur Leblanc, juste une fois.');
INSERT INTO citations VALUES('dinerdecons', 'Et voilà on a les droits !!! Olalalalalalalala ! Et pour pas cher à mon avis, Il a marché, il a marché à fond le gars !');
INSERT INTO citations VALUES('dinerdecons', 'Il a oublié ma femme ... Il fait le clown pendant 5 minutes et il oublie ma femme !');
INSERT INTO citations VALUES('dinerdecons', 'Ah oui, j''ai fait la boulette...');
INSERT INTO citations VALUES('dinerdecons', 'Ca dépasse tout c''que j''ai pu imaginer !');
INSERT INTO citations VALUES('dinerdecons', 'On a repoussé les limites là...');
INSERT INTO citations VALUES('dinerdecons', 'Mais vous couchez avec tous vos auteurs dites-moi ?');
INSERT INTO citations VALUES('dinerdecons', 'Dans l''cul l''OM dans l''cul Lulu dans l''cuul ! ');
INSERT INTO citations VALUES('dinerdecons', 'Mais il est hors concours celui-là... ');
INSERT INTO citations VALUES('dinerdecons', 'Bah je peux pas Charlotte m''a demandé d''enregistrer le patinage artistique elle est partie chez sa mère !');
INSERT INTO citations VALUES('dinerdecons', 'Mais il est malade ce type je suis pas avec sa femme !');
INSERT INTO citations VALUES('dinerdecons', 'Vous n''êtes pas avec Madame Brochant ?');
INSERT INTO citations VALUES('dinerdecons', 'Mais pas du tout je suis avec la femme de mon controleur fiscal ! ');
INSERT INTO citations VALUES('dinerdecons', 'Bonsoir Monsieur Menot, voulez vous être assez aimable pour me passer Madame Cheval je vous prie ! Vous m''avez parfaitement reconnu Monsieur Menot, je vous vois demain matin à neuf heures comme d''habitude et on reprend tout depuis le début ! Maintenant passez moi ma femme je vous prie ! Charlotte, non ne m''explique rien, je veux que tu quittes cet endroit immédiatement tu m''entends ? A la seconde ! Comment ? ah bien sûr que tu te rhabilles évidemment que tu te rhabilles ! Heu Charlotte je ne suis pas seul, je ne peux pas te parler maintenant on causera à la maison. Charlotte ! J''t''avais enregistré le patinage artistique...');
INSERT INTO citations VALUES('dinerdecons', 'Je suis avec celle de mon contrôleur fiscal, un connard qui me persécute depuis des mois, je suis en train de sauter sa femme !');
INSERT INTO citations VALUES('dinerdecons', 'J''le rappelle !');
INSERT INTO citations VALUES('dinerdecons', 'Mais quel connaaaard !');

INSERT INTO citations VALUES('classeamericaine', 'Ah voilà enfin le roi d''la classe ! L''homme trop bien sapé !... Abitbol !');
INSERT INTO citations VALUES('classeamericaine', 'Ah, encore une chose, je vous conseille d''éviter la mousse au chocolat du patron !');
INSERT INTO citations VALUES('classeamericaine', 'La vache !!!');
INSERT INTO citations VALUES('classeamericaine', 'Enfin, si ça t''plaît…');
INSERT INTO citations VALUES('classeamericaine', 'Tu n''es vraiment pas très sympa.');
INSERT INTO citations VALUES('classeamericaine', 'Attention : ce flim n''est pas un flim sur le cyclimse.');
INSERT INTO citations VALUES('classeamericaine', 'Ça doit être les burgers…');
INSERT INTO citations VALUES('classeamericaine', 'C''est lui, là ! Qui, le jus de tomate ?');
INSERT INTO citations VALUES('classeamericaine', 'Le train de tes insultes roule sur les rails de mon indifférence.');
INSERT INTO citations VALUES('classeamericaine', 'Tu fais un amalgame entre la coquetterie et la classe !');
INSERT INTO citations VALUES('classeamericaine', 'Je préfère partir plutôt que d’entendre ça plutôt que d’être sourd !');
INSERT INTO citations VALUES('classeamericaine', 'J’aimerais bien que tu restes. On va manger des chips. Tu entends ? Des chips ! C’est tout ce que ça te fait quand je te dis qu’on va manger des chips ?');
INSERT INTO citations VALUES('classeamericaine', 'Monde de merde.');
INSERT INTO citations VALUES('classeamericaine', 'Tiens regarde, les anglais ont débarqués, on va être obligés de passer par derrière. Tu sais par ce tunnel tout sombre qui sent pas très bon.');
INSERT INTO citations VALUES('classeamericaine', 'Blablabla, j’ai les bonbons qui collent au papier.');
INSERT INTO citations VALUES('classeamericaine', 'Écoute-moi bien mon petit José, tu baises les ménagères, bien : tu dois avoir le cul qui brille ! Mais c’est pas ça qu’on appelle la classe…');
INSERT INTO citations VALUES('classeamericaine', 'Hey, l’homme qui fait rêver les ménagères ! Moi j’les baise, les ménagères, hein ! C’est pas vrai ?');
INSERT INTO citations VALUES('classeamericaine', 'Allons, vieux, même dans les grands restaurants on crache dans les plats, alors dans ce taudis, je vois pas pourquoi ils se feraient chier. Allez, je vous laisse manger, bon appétit.');
INSERT INTO citations VALUES('classeamericaine', 'J’ai connu un mec de droite une fois, il avait dix fois plus de classe.');
INSERT INTO citations VALUES('classeamericaine', 'Merci de m’appeler tâcheron ! Ça fait toujours plaisir à entendre, surtout de la part de deux pédés.');
INSERT INTO citations VALUES('classeamericaine', 'J’en ai pour plus d’une barre de fringues sur moi. Alors, va te faire mettre !');
INSERT INTO citations VALUES('classeamericaine', 'Bien ! Considère qu’on n’est plus amis, Abitbol !');
INSERT INTO citations VALUES('classeamericaine', 'Non mais pour qui tu me prends, je rêve ! La fromagerie en bas de chez moi elle vendait trois choses : du fromage, des ouiches lorraines et de la bouffe chinoise... Alors toi, mec, avec tes régimes à la con, tu me fais bien marrer : t’as devant toi le spécialiste de la ouiche lorraine !');
INSERT INTO citations VALUES('classeamericaine', 'Quoi "patron" !? Tu veux que je le dise à tout le monde que ton vrai nom c''est Travers de porc sel poivre ?');
INSERT INTO citations VALUES('classeamericaine', 'Je me permet d''interrompre ce flim parce qu''on se fout un peu de ma gueule. C''est du vol et du plagiat... J''aime pas trop les voleurs et les fils de pute !');
INSERT INTO citations VALUES('classeamericaine', 'Au fait j''y pense, Callaghan il devrait pouvoir vous aider. Depuis le temps qu''il est là payé à rien foutre, autant qu''il serve à quelque chose !... Ce gros PORC !');
INSERT INTO citations VALUES('classeamericaine', 'Comprenez-moi mes amis, c''est mon fils, ma bataille, c''est le fruit de mes entrailles, quoi ! J''avais un nom et une adresse, ben je lui ai donnés !');
INSERT INTO citations VALUES('classeamericaine', 'Vous dites que j''aille me faire foutre ? OK, j''y vais !');
INSERT INTO citations VALUES('classeamericaine', 'Y avait rien de sexuel entre nous ! Je vous dis ça parce que je me suis souvent fait traité de pédale, de salope, et c''est facile de traiter les gens de pédés tout ça parce que deux garçons vivent ensemble dans un ranch et portent des pantalons en cuir !');
INSERT INTO citations VALUES('classeamericaine', 'Je rêve d''un bon bain dans une Bôonne Aubeerge... Ah j''te jure... j''ai les pastèques !');
INSERT INTO citations VALUES('classeamericaine', 'Mais qu''est-ce qui te prend à dire "YEP", comme ça ?');
INSERT INTO citations VALUES('classeamericaine', 'Tu sais,... tes excuses, tu peux te les coller au cul, tout comme ton beefsteak, sauf que le beefsteak, ça sert à rien, le patron l''a déjà fait, il a craché dessus.');
INSERT INTO citations VALUES('classeamericaine', 'George est un fasciste de merde ! UN FASCISTE DE MERDE !!!');
INSERT INTO citations VALUES('classeamericaine', 'Vous êtes très gentil ...euh attention ! J''ai bien dit "gentil", j''ai pas dit "homosexuel", hein !');
INSERT INTO citations VALUES('classeamericaine', 'Ca va plus du tout. J''ai plus envie de boire, ni de manger... J''ai plus envie de me peigner. J''suis limite nervous breakdown... Wah ! Et puis merde ! J''ai même plus envie de me laver...');
INSERT INTO citations VALUES('classeamericaine', 'Sheraf... Tu connais pas Sheraf ?!... C''est un groupe, ils étaient number one. (...) REGARDE ! J''me suis niqué les mains, moi, avec cette SALOPERIE DE COLLEC'' DE PIN''S A LA CON !');
INSERT INTO citations VALUES('classeamericaine', 'Rester en ville malgré les menaces de George, j''trouve ça drôlement courageux de la part d''un pédé comme vous !');
INSERT INTO citations VALUES('classeamericaine', 'Arrêtez de dire ça! Je ne suis pas gentil, c''est pas vrai ! Quand je m''enerve, je me mets dans des états dingues, je suis méconnaissable !');
INSERT INTO citations VALUES('classeamericaine', 'Si je fais journaliste, c''est évidemment pour être célèbre, moi j''veux être connu, tu sais pourquoi ? Pour niquer les gonzesses !');
INSERT INTO citations VALUES('classeamericaine', 'Vous savez, j''arrivais d''Italie, de Turin. A l''époque, j''étais supporter de la Juventus...');
INSERT INTO citations VALUES('classeamericaine', 'Pour être tout à fait exact,... je pense que t''es un OUF, toi ! un OUF MALADE !');
INSERT INTO citations VALUES('classeamericaine', 'Qu''est-ce que j''apprend Frankie, espèce de malhonnête !?... Il parait que t''as des propos intolérables... Où y a pas de tolérance !? (...) ENCULÉ DE TA RACE!');
INSERT INTO citations VALUES('classeamericaine', 'C''était un soir. J''avais le spleen, le blues...');
INSERT INTO citations VALUES('classeamericaine', 'Si tu veux me parler, envoie-moi un... FFFAX !');
INSERT INTO citations VALUES('classeamericaine', 'Oui je pourrais,... mais d''abord, faut sucer !');
INSERT INTO citations VALUES('classeamericaine', 'Bon, maintenant t''arrête ! Parce que j''te ferais dire que pendant qu''on parle, Peter il a la méga-chiasse ! Alors un peu de dignité s''te plait !');
INSERT INTO citations VALUES('classeamericaine', 'George finit par se lasser de moi, alors il est parti avec une quebequoise... une belle p''tite salope !');

INSERT INTO citations VALUES('bernie', 'C’est la société qui est bien foutue, elle fout des uniformes aux cons pour qu’on les reconnaisse.');
INSERT INTO citations VALUES('bernie', 'En ce moment, je fais toujours le même rêve. Je nage dans la Seine et tout d’un coup, j’avale un rat. Alors j’étouffe et pis je coule. En bas, y a des huîtres, elles m’attrappent les chevilles. Alors je vomis le rat sur les huîtres, le rat il attaque les huitres, je remonte à la surface, j’prends une péniche sur la tête et là, j’me réveille.');
INSERT INTO citations VALUES('bernie', 'Je vais tellement t’enculer que quand tu bailleras on verra le jour !');
INSERT INTO citations VALUES('bernie', 'Dis papa, comment ça se passe avec le sexe des filles ? J’sais pas, j’fais qu’les enculer !');
INSERT INTO citations VALUES('bernie', '- Donald, je te donnerai tout ce que tu voudras. 100 000 en liquide... Si tu préfères j’ai des Nations monétaires à 6.25, je peux les placer en obligation sur ton nom. - Je préfère t’enculer.');
INSERT INTO citations VALUES('bernie', '- Fini la branlette ! - M’en fous j’suis gaucher !');
INSERT INTO citations VALUES('bernie', 'Je m’appelle Bernie Noël et j’aime bien les hyènes. Parce que la hyène c’est un animal dont on parle jamais alors que c’est un animal qui peut être, qui peut être très important. Parce que moi je trouve que être ami avec une hyène souvent c’est plus important qu’être ami avec, avec des vrais amis. C’est... Elle vous protège. Si y’avait du danger et ben « Et ben moi, et... je suis ami avec une hyène » Alors la évidement !');
INSERT INTO citations VALUES('bernie', 'Casse toi ! Des connards comme toi j’en vois 10 par jours. Alors si tu te tailles pas tout de suite j’te fait enculer à coup de rosiers.');
INSERT INTO citations VALUES('bernie', 'C’est pas moi ! Il a glissé ! C’est parce qu’il pleut !');
INSERT INTO citations VALUES('bernie', 'C’qui est embêtant dans les oiseaux c’est le bec.');
INSERT INTO citations VALUES('bernie', 'Et les enculés, vous avez entendu ? J’ai un otage finalement ! Alors si ça continu je la tue, n’importe comment, avec des pierres avec un marteau, de toute façon j’en ai rien à foutre je suis fou !');
INSERT INTO citations VALUES('bernie', '- 400 000 francs, tu te rends compte de ce que ça représente ? - Je sais que c’est pas énorme, mais ça me permettra de tenir quelques jours, quelques semaines, après je ferai comme les autres, j’irai au chômage.');
INSERT INTO citations VALUES('bernie', 'J’ai toujours su que tu finirais pute.');
INSERT INTO citations VALUES('bernie', 'Et je sais pas qui c’était les enculés d’en face, mais ça doit être des drôles d’enculés parce que s’en prendre à un bébé !');
INSERT INTO citations VALUES('bernie', 'Je m’appelle Bernie Noël, j’ai 29 ans, bientôt 32. Je... Je suis député. Je possède un chat, Momo. Momo est un chat depuis de nombreuses années mais c’est également un félin. Voilà c’est Momo... kikikikikik.');
INSERT INTO citations VALUES('bernie', '- Si tu es resté ici après tes 18 ans c’est pas un hasard. - Si je suis resté ici c’est parce qu’il y avait du travail ici. C’était même plutôt intelligent de rester ici quand je pense à tous les crétins qui sont partis en ricanant, beh maintenant ils ricanent au chômage.');
INSERT INTO citations VALUES('bernie', 'You take Dollar?');
INSERT INTO citations VALUES('bernie', 'Where is mum? She is in the bathroom. Where is dad? He is not at home. Why? I don’t know.');
INSERT INTO citations VALUES('bernie', 'On fait moins le malin maintenant, hein ? On fait moins le malin !');

INSERT INTO citations VALUES('terminator', 'Hasta la vista, baby !');
INSERT INTO citations VALUES('terminator', 'No problemo!');
INSERT INTO citations VALUES('terminator', 'Donne tes fringues !');
INSERT INTO citations VALUES('terminator', 'Sarah Connor ?');
INSERT INTO citations VALUES('terminator', 'I''ll be back.');
INSERT INTO citations VALUES('terminator', 'You''re terminated, fucker.');

INSERT INTO citations VALUES('rambo', 'La Birmanie est une zone de guerre.');
INSERT INTO citations VALUES('rambo', 'Je préfère mourir pour une cause que vivre pour rien !');
INSERT INTO citations VALUES('rambo', 'Vous avez des armes ? Alors vous ne changerez rien.');
INSERT INTO citations VALUES('rambo', 'Holy shit!');
INSERT INTO citations VALUES('rambo', 'Merde !');

INSERT INTO citations VALUES('toutoune', 'Ta mère est tellement poilue que quand elle sort le chien c''est elle qu''on caresse.');
INSERT INTO citations VALUES('toutoune', 'Ta mère est tellement grosse que quand elle sort ça fait une eclipse.');
INSERT INTO citations VALUES('toutoune', 'Ta mere est tellement grosse que lorsqu''elle va chez mammouth on l''appelle patron.');
INSERT INTO citations VALUES('toutoune', 'Ta mère est tellement moustachue que quand elle bouffe une banane on dirait un film de cul.');
INSERT INTO citations VALUES('toutoune', 'Ta mere est tellement grosse que quand elle mange du caramel elle en chie des mars.');
INSERT INTO citations VALUES('toutoune', 'Ta mère est tellement radine que quand elle vomit, elle sert les dents pour garder les gros morceaux.');
INSERT INTO citations VALUES('toutoune', 'Ta mère est tellement radine que quand elle s''essuie le cul, elle utilise le papier des deux côtés.');
INSERT INTO citations VALUES('toutoune', 'Ta mère est tellement petite que sa tête pue des pieds.');
INSERT INTO citations VALUES('toutoune', 'Ta mère est tellement grosse qu''elle ne rentre pas dans /dev/null');
INSERT INTO citations VALUES('toutoune', 'Ta mère c''est comme Mario, elle saute pour avoir des pièces !');
INSERT INTO citations VALUES('toutoune', 'Ta mère est tellement grosse que même en JPG elle fait 170MO ');
INSERT INTO citations VALUES('toutoune', 'Ta mère elle est tellement grosse que quand elle passe devant ton PC il y a le Wi-fi qui se coupe !');
INSERT INTO citations VALUES('toutoune', 'ta mère elle est tellement petite que meme de près elle a l''air loin');

INSERT INTO citations VALUES('villiers', 'Mais on s''en fout qu''t''aime la politique, nous on aime la France !');
INSERT INTO citations VALUES('villiers', '"J''aime la politique, j''aime la politique"');
INSERT INTO citations VALUES('villiers', 'J''ai mangé un Kebac à Budapest devant les bains Turcs');

INSERT INTO citations VALUES('snatch', 'T''aimes les chians ?');

INSERT INTO citations VALUES('simpsons', 'Wouh ! Pinaise !');

INSERT INTO citations VALUES('spiderman', 'With great power comes great responsibility.');

INSERT INTO citations VALUES('neuneu', '10:35 <@dibalo> faut que je réussisse à la tenir aussi :)');
INSERT INTO citations VALUES('neuneu', '11:01 <@KheOps> bon je discute le bout de gras avec Sof c''est rigolo');
INSERT INTO citations VALUES('neuneu', '17:55 <@KheOps> dibalo: Ludivine a du riz basmati');
INSERT INTO citations VALUES('neuneu', '17:55 <@bebui> une petite giclée dans ton riz et il collera !');
INSERT INTO citations VALUES('neuneu', 'debout antoine KheOps bebui Duncan MacLord');
INSERT INTO citations VALUES('neuneu', '<@bebui> KheOps: tu rentres ce soir ? (a l''appart pas dans ludi ^^)');
INSERT INTO citations VALUES('neuneu', '11:14 <@dibalo> j''avoue que ma bite est grosse et elle a du mal à jouir en qqes secondes');
INSERT INTO citations VALUES('neuneu', '13:38 <@KheOps> je me demande ce que ça fait de péter dans une flûte de pan');
INSERT INTO citations VALUES('neuneu', 'no pedalos !');

INSERT INTO citations VALUES('chucknorris', 'Chuck Norris is 1/8th Cherokee. This has nothing to do with ancestry, the man ate a fucking Indian.');
INSERT INTO citations VALUES('chucknorris', 'There is no chin behind Chuck Norris'' beard. There is only another fist.');
INSERT INTO citations VALUES('chucknorris', 'In fine print on the last page of the Guinness Book of World Records it notes that all world records are held by Chuck Norris, and those listed in the book are simply the closest anyone else has ever gotten.');
INSERT INTO citations VALUES('chucknorris', 'The chief export of Chuck Norris is pain.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris is currently suing NBC, claiming Law and Order are trademarked names for his left and right legs.');
INSERT INTO citations VALUES('chucknorris', 'The Great Wall of China was originally created to keep Chuck Norris out. It failed misserably.');
INSERT INTO citations VALUES('chucknorris', 'Crop circles are Chuck Norris'' way of telling the world that sometimes corn needs to lie the fuck down.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris once commented, "There are few problems in this world that cannot be solved by a swift roundhouse kick to the face. In fact, there are none."');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris once ate an entire ream of rice paper and shat out origami swans and Mister Miyagi from Karate Kid.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris is ten feet tall, weighs two-tons, breathes fire, and could eat a hammer and take a shotgun blast standing.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris is a man of few words. Chuck Norris is not a man of few roundhouse kicks to the face.');
INSERT INTO citations VALUES('chucknorris', 'The Four Horsemen of the Apocalypse actually live in Chuck Norris''s nutsack.');
INSERT INTO citations VALUES('chucknorris', 'When observing a Chuck Norris roundhouse kick in slow motion, one finds that Chuck Norris actually rapes his victim in the ass, smokes a cigarette with Dennis Leary, and then roundhouse kicks them in the face.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris put humpty dumpty back together again, only to roundhouse kick him in the face. Later Chuck dined on scrambled eggs with all the king''s horses and all the king''s men. The king himself could not attend for unspecified reasons. Coincidentally, the autopsoy revealed the cause of death to be a roundhouse kick to the face. There is only one King.');
INSERT INTO citations VALUES('chucknorris', 'When Chuck Norris played golf for money, chuck marked down a hole in 0 every time, a pro at the golf club, said to Chuck: "excuse me sir, but you cant score zero on a hole". Chuck Norris turned towards the man and said, im Chuck Norris, the man then proceeded to pour gas over his body and set himself on fire because that would be less painful than getting roundhouse kicked by Chuck Norris, Chuck Norris roundhouse kicked him in the face anyways.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris made Ellen Degeneres straight.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris kicked Neo out of Zion , now Neo is "The Two"');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris'' iPod came with a real charger instead of just a USB cord');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris knows where Carmen Sandiego is.');
INSERT INTO citations VALUES('chucknorris', 'Rudolph has a red nose because he got lippy and Chuck Norris roundhouse kicked him across the face several times');
INSERT INTO citations VALUES('chucknorris', 'China was once bordering the United States, until Chuck Norris roundhouse kicked it all the way through the Earth.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris is what Willis was talking about');
INSERT INTO citations VALUES('chucknorris', 'If you have five dollars and Chuck Norris has five dollars, Chuck Norris has more money than you.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris sent Jesus a birthday card on December 25th and it wasn''t Jesus’ birthday. Jesus was to scared to correct Chuck Norris and to this day December 25th is known as Jesus'' birthday.');
INSERT INTO citations VALUES('chucknorris', 'When Chuck Norris had surgery, the anesthesia was applied to the doctors.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris once broke the land speed record on a bicycle that was missing its chain and the back tire.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris once kicked a baby elephant into puberty');
INSERT INTO citations VALUES('chucknorris', 'Multiple people have died from Chuck Norris giving them the finger.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris once tried to wear glasses. The result was him seeing around the world to the point where he was looking at the back of his own head.');
INSERT INTO citations VALUES('chucknorris', 'Pee Wee Herman got arrested for masturbating in public. The same day, Chuck Norris got an award for masturbating in public.');
INSERT INTO citations VALUES('chucknorris', 'Once a grizzly bear threatened to eat Chuck Norris. Chuck showed the bear his fist and the bear proceeded to eat himself, because it would be the less painful way to die.');
INSERT INTO citations VALUES('chucknorris', 'If Chuck Norris is late, time better slow the fuck down');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris sleeps with a night light. Not because Chuck Norris is afraid of the dark, but the dark is afraid of Chuck Norris');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris can touch MC Hammer.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris ordered a Big Mac at Burger King, and got one.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris always has sex on the first date. Always.');
INSERT INTO citations VALUES('chucknorris', 'A Handicap parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to Chuck Norris and that you will be handicapped if you park there.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris frequently donates blood to the Red Cross. Just never his own.');
INSERT INTO citations VALUES('chucknorris', 'There is no such thing as tornados. Chuck Norris just hates trailer parks.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris never cries, because of this when he''s sad he roundhouse kicks himself and it makes him feel better since he knows he is the only one who can survive the roundhouse.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris does not procreate, he breeds');
INSERT INTO citations VALUES('chucknorris', 'When asked what type of vehicle he drives, Chuck Norris responded slyly with "Don''t you mean what kind of vehicle drives me?"');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris'' evil twin brother, Richard Simmons, once approached Chuck with the hope of reconciliation, but at the sight of Richard''s curly, well kept hair, Chuck Norris became so enraged that he turned green with hate and ripped Richard Simmons arms and legs off. This action was the originffended or hurt, he may be just trying to tell you he likes your hat.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris went looking for a bar but couldn’t find one. He walked to a vacant lot and sat thernal pilot for Star Trek Next Generation, Chuck Norris can be seen powering the USS Enterprise warp drive with his roundhouse kicks.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris isn’t lactose intolerant. He just doesn’t put up with lactose’s shit.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris doesn’t eat. Rather he kicks');
INSERT INTO citations VALUES('chucknorris', 'When Chuck Norris’s wife burned the turkey one Thanksgiving, Chuck said, “Don’t worry about it honey,” and went into his backyard. He came back five minutes later with a live turkey, ate it whole, and when he threw it up a few seconds later it was fully cookof the troops back into Chuck''s balls. Chuck pulled out; roundhouse kicked Cindy in the face and told her, "Don''t ever waste my time again."');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris can piss into gale force winds.');
INSERT INTO citations VALUES('chucknorris', 'There are no disabled people. Only people who have met Chuck Norris.');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norrmuch debate, President Truman decided to drop the atomic bomb on Hiroshima rather than the alternative of sending Chuck Norris. It was more "humane".');
INSERT INTO citations VALUES('chucknorris', 'Chuck Norris doesn''t see dead people. He makes people dead.');
